### PR TITLE
Remove scalaz-bintray resolver

### PR DESCRIPTION
**Pull request by kubukoz**

### CODE REVIEW

**Comment by kubukoz** [comment]
Failing with

```
[info] - authorization for private projects *** FAILED ***
[info]   List("itm-d474d47a87034829afa13727cabd2a40") was not equal to List("itm-61a42f0b92244ef8a6410f83568c3b36") (ItemsDaoSpec.scala:139)
```

which is strange. Removing the resolver shouldn't have any effect, as the only library in that repository is `scalaz-stream`, which `dependency` has no dependency on (even transitive, it seems).

**Comment by kubukoz** [comment]
Looks like a flaky test...

**Comment by ericluria** [comment]
I think the `scalaz-stream` dependency was there because at one point there were issues either resolving Play framework or something with specs2. Either way, that was well over a year ago so it was likely fixed if we no longer see the issue.

We actually have this dependency in all of our projects. Good to know that it can be removed now!

**Comment by kubukoz** [comment]
I don't know about the dependency in other projects, but the resolver isn't needed anymore :P it's mentioned in the scalaz-stream readme.

**Pull request merged**
