### PR TITLE
FDN-2371: Upgrade libraries com.datadoghq, io.flow

### PR DESCRIPTION
**Pull request by abhidwivedi2701**
- com.datadoghq
  - dd-java-agent (1.33.0 => 1.34.0)
- io.flow
  - lib-event-sync-play28 (0.6.49 => 0.6.55)
  - lib-log (0.2.18 => 0.2.21)
  - lib-metrics-play28 (1.0.86 => 1.0.89)
  - lib-play-play28 (0.7.99 => 0.8.2)
  - lib-test-utils-play28 (0.2.30 => 0.2.32)
  - lib-usage-play28 (0.2.45 => 0.2.49)
  - sbt-flow-linter (0.0.55 => 0.0.56)

### CODE REVIEW

**Comment by flow-tech** [comment]
helm diff detected no changes for dependency-api

helm diff detected no changes for dependency-www

**Comment by flow-tech** [comment]
helm diff detected no changes for dependency-api

helm diff detected no changes for dependency-www

**Comment by flow-tech** [comment]
helm diff detected no changes for dependency-api

helm diff detected no changes for dependency-www

**Comment by flow-tech** [comment]
helm diff detected no changes for dependency-api

helm diff detected no changes for dependency-www

**Review by gheine — APPROVED** [review]

**Pull request merged**
