### PR TITLE
FDN-2353: Skip major version upgrades of binaries (eg. scala version)

### PR DESCRIPTION
**Pull request by gheine**

### CODE REVIEW

**Comment by flow-tech** [comment]
helm diff detected no changes for dependency-api

helm diff detected no changes for dependency-www

**Comment by flow-tech** [comment]
helm diff detected no changes for dependency-api

helm diff detected no changes for dependency-www

**Comment by flow-tech** [comment]
helm diff detected no changes for dependency-api

helm diff detected no changes for dependency-www

**Comment by flow-tech** [comment]
helm diff detected no changes for dependency-api

helm diff detected no changes for dependency-www

**Review by nicolagi — APPROVED** [review]

**Pull request merged**
